
== Introducción
Actualmente cada hotel tiene una solución local de reservaciones, pero tiene el problema de generar inconsistencias, errores y dificulta el control centralizado.
Este sistema busca globalizar todas las reservaciones con una plataforma centralizada que sea escalable, segura y con buen rendimiento.

== Oportunidad de Negocio
Transformar la gestión de reservaciones de un costo operativo a un aventaja competitiva. Un sistema unificado permitirá implementar precios dinámicos y políticas de ocupación avanzadas, incrementando los ingresos y mejorando la satisfacción del cliente.

== QA importantes
- Seguridad (7) - Podría cambiar la Arq
- Integridad (5) - Podría cambiar la Arq
- Disponibilidad (4) - Podría cambiar la Arq
- Rendimiento (4) - Podría cambiar la Arq
- Interoperabilidad (3)
- Escalabilidad (3)
- Usabilidad (2)
- Portabilidad (0)

= Escenario de Rendimiento - Software de Gestión de Hoteles

== Fuente
Un recepcionista del hotel

== Estímulo
Solicita la disponibilidad de habitaciones para una fecha específica durante temporada alta

== Artefacto
Módulo de reservas del sistema de gestión de la cadena hotelera

== Entorno
El sistema está en operación normal, con múltiples usuarios concurrentes realizando consultas y reservas (pico de carga en temporada alta)

== Respuesta
El sistema procesa la solicitud, accede a la base de datos centralizada de hoteles, recupera la información y muestra las habitaciones disponibles en pantalla

== Medida
* La respuesta debe generarse en *menos de 2 segundos* para consultas de disponibilidad
* Confirmación de reserva en *menos de 5 segundos*
* Soporta al menos *500 usuarios concurrentes* sin degradación perceptible del servicio

== Evaluación
* Importancia para el negocio: H
* Dificultad técnica: M
