
== ADR

---

=== ADR-001: Priorización de Seguridad sobre otros ASRs

*Estado:* Aceptado

*Contexto y Drivers:* Basados en el *CRN-10* los _Huéspedes_ ingresarán al sistema datos personales y sus tarjetas o métodos de pago y es inaceptable que estos datos estén en riesgo (como clonación de tarjetas por ejemplo) ya que aparte del peligro para los _Huéspedes_ podría resultar en un problema legal con un gran impacto para los interesados.

*Opciones consideradas:* 

* Se consideró que a mayor seguridad el rendimiento puede disminuir.

* Soluciones consideradas:

** Uso de una base de datos relacional para mantener la integridad
*** Garantiza transacciones ACID

** Táctica *No almacenar datos sensibles* para mejorar la seguridad de la información del _Huésped_
*** Se debe delegar esa responsabilidad

** Uso de un patrón de diseño *Proxy* para mejorar la seguridad
*** Por ejemplo, verificar si un usuario está autorizado para acceder a cierta información

** Façade entre la *Pasarela externa de pagos* y el *Sistema de reservaciones*

** *Forzar Comunicación Segura (HTTPS/TLS)** en todos los endpoints para mitigar ataques Man-in-the-Middle

*Decisión:* Se usarán las siguientes soluciones:

* Uso de una base de datos relacional
** Es confiable, mantiene integridad (ACID)

* *No almacenar datos sensibles*
** Repartimos repsonsabilidades a otro módulo para mejorar la concentración de esfuerzos

* Façade entre la *Pasarela de pagos* y el *Sistema de reservaciones*
** Evitamos la comunicación directa con otro sistema
** No se tiene acceso a métodos no necesarios

* *Forzar Comunicación Segura (HTTPS/TLS)** en todos los endpoints
** Se mitigan ataques Man-in-the-Middle
** Mejoramos la seguridad al comunicarse entre módulos

*Consecuencias:*

* El uso de bases de datos relacionales (como PostgreSQL o MySQL) es confiable por su estabilidad y madurez, sin embargo, el esquema es rigido (un cambio es caro)
* Al delegar la responsabilidad a otro módulo de almacenar datos sensibles se debe tener en cuenta que la comunicación con ese módulo debe ser muy segura para evitar ataques MitM, lo cuál cubrimos usando *HTTPS/TLS*. La desventaja es la dependencia con el módulo al que se delegó la información 
* Mediante la *Façade* reducimos acoplamiento y la superficie de ataque, mejorando la flexibilidad y seguridad a futuro, pero hay que escalarla bien para no generar un cuello de botella
* Al usar *HTTPS/TLS* es importante renovar y configurar los certificados correctamente pero a cambio nos aseguramos que hablamos con el servidor correcto (*TLS*) y obtenemos seguridad entre _módulos internos_

== Matriz de Trazabilidad

[cols="1,1,1,1"]

|===

|Driver
|Decisión de Diseño
|Artefactos Afectados
|Estado

| QAS: Seguridad
| Utilizar una Façade para la comunicación con la Pasarela de pagos
| Vista de implementacion
| Cumple

|===